=== eco-stake/validator-registry/src/validator-registry/profile.schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"title": "Root", 
	"type": "object",
	"required": [
		"name"
	],
	"properties": {
		"name": {
			"$id": "#root/name", 
			"title": "Name", 
			"type": "string",
			"default": "",
			"examples": [
				"ECO Stake ðŸŒ±"
			],
			"pattern": "^.*$"
		},
		"identity": {
			"$id": "#root/identity", 
			"title": "Identity", 
			"type": "string",
			"default": "",
			"examples": [
				"5992A6D423A406D6"
			],
			"pattern": "^.*$"
		},
		"website": {
			"$id": "#root/website", 
			"title": "Website", 
			"type": "string",
			"default": "",
			"examples": [
				"https://ecostake.com"
			],
			"pattern": "^http.*$"
		},
		"description": {
			"$id": "#root/description", 
			"title": "Description", 
			"type": "object",
			"required": [
				"overview"
			],
			"properties": {
				"overview": {
					"$id": "#root/description/overview", 
					"title": "Overview", 
					"type": "string",
					"default": "",
					"pattern": "^.*$"
				},
				"team": {
					"$id": "#root/description/team", 
					"title": "Team", 
					"type": "string",
					"default": "",
					"pattern": "^.*$"
				},
				"security": {
					"$id": "#root/description/security", 
					"title": "Security", 
					"type": "string",
					"default": "",
					"pattern": "^.*$"
				}
			}
		},
		"contacts": {
			"$id": "#root/contacts", 
			"title": "Contacts", 
			"type": "object",
			"required": [],
			"properties": {
				"telephone": {
					"$id": "#root/contacts/telephone", 
					"title": "Telephone", 
					"type": "string"
				},
				"email": {
					"$id": "#root/contacts/email", 
					"title": "Email", 
					"type": "string"
				},
				"telegram": {
					"$id": "#root/contacts/telegram", 
					"title": "Telegram", 
					"type": "string"
				},
				"twitter": {
					"$id": "#root/contacts/twitter", 
					"title": "Twitter", 
					"type": "string"
				},
				"discord": {
					"$id": "#root/contacts/discord", 
					"title": "Discord", 
					"type": "string"
				},
				"others": {
					"$id": "#root/contacts/others", 
					"title": "Others", 
					"type": "object",
					"required": [],
					"additionalProperties": true
				}
			}
		}
	}
}

=== eco-stake/validator-registry/src/validator-registry/finteh/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "finteh",
  "identity": "EEEA76E0A487DDCB",
  "website": "https://finteh.org/nodes",
  "description": {
    "overview": "we can help another validators move to bare metal servers"
  },
  "contacts": {
    "telegram": "finteh",
    "twitter": "finteh"
  }
}

=== eco-stake/validator-registry/src/validator-registry/whispernode/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "WhisperNodeü§ê",
  "identity": "C99B3A6836BF0CB8",
  "website": "https://WhisperNode.com",
  "description": {
    "overview": "Whispernode is a grassroots validator team that‚Äôs 100% focused on decentralization, security, & the cosmos ecosystem. We started with just one validator on Secret Network. We love the Web3 space and consider ourselves blessed to be able to do what we do everyday.",
    "team": "WhisperNode is now a Cosmos focused subbrand of Liquify.io. Our team now combines WhisperNode's Cosmos expertise with Liquify's long-standing excellence in RPC and Infra provisioning",
    "security": "We strive to be incrementally better at what we do every single day, and thus reinvest a lot of our resources from delegators into improving WhisperNode (more on this below). WhisperNode works 24/7 to ensure that delegators can sleep peacefully, knowing their funds are #SAFU. We use TMKMS remote signers to ensure we NEVER double-sign, and run infrastructure across the globe to maintain a high level of decentralization + failover."
  },
  "contacts": {
    "telephone": "",
    "email": "security@whispernode.com",
    "telegram": "BKBlockchain",
    "twitter": "whispernode",
    "discord": "https://discord.gg/4E5KZsRtjE",
    "others": {
      "emergency": ""
    }
  }
}

=== eco-stake/validator-registry/PantheaEU/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "Panthea EU",
  "identity": "8CE646C2F8F60AF7",
  "website": "https://www.panthea.eu",
  "description": {
    "overview": "Secure and reliable EU based validator operations.",
    "team": "",
    "security": ""
  },
  "contacts": {
    "telephone": "",
    "email": "validator@panthea.eu",
    "telegram": "PantheaEU",
    "twitter": "PantheaEU",
    "discord": "",
    "others": {
      "emergency": ""
    }
  }
}

=== eco-stake/validator-registry/src/validator-registry/dForce/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "dForce",
  "identity": "AB99C8D824487B05",
  "website": "https://dforce.network",
  "description": {
    "overview": "dForce is a decentralized finance protocol matrix covering decentralized stablecoin(USX), lending, and trading, serving as DeFi infrastructure in Web3. We provide affordable staking service to atom holders and to contribute to Cosmos governance."
  },
  "contacts": {
    "telephone": "",
    "email": "",
    "telegram": "dforcenet",
    "twitter": "dForcenet",
    "discord": "https://discord.com/invite/c2PC8SM",
    "others": {
      "emergency": ""
    }
  }
}

=== eco-stake/validator-registry/src/validator-registry/Moonbridge/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "Moonbridge",
  "identity": "6F7C6C0637B4BD6F",
  "website": "https://moonbridge.org",
  "description": {
    "overview": "Build your bridge to the future of decentralized finance",
    "team": "",
    "security": ""
  },
  "contacts": {
    "telephone": "",
    "email": "",
    "telegram": "",
    "twitter": "",
    "discord": "",
    "others": {
      "emergency": ""
    }
  }
}

=== eco-stake/validator-registry/src/validator-registry/Omnistake.com/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "Omnistake.com",
  "identity": "A5F79527539464C1",
  "website": "https://omnistake.com",
  "description": {
    "overview": "Omnistake is a trusted non custodial staking provider, currently operating across multiple blockchains: SUI, ICP, Saga, Canto, Cartesi, Near."
  },
  "contacts": {
    "telephone": "",
    "email": "support@omnistake.com",
    "telegram": "",
    "twitter": "omnistake",
    "discord": "",
    "others": {
      "emergency": ""
    }
  }
}

=== eco-stake/validator-registry/emidev98/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "emidev98",
  "identity": "96D529BB4E74A1A0",
  "website": "https://github.com/emidev98",
  "description": {
    "overview":"Core developer at Terra"
  },
  "contacts": {
    "telephone": "",
    "email": "engineering@terra.money",
    "telegram": "emidev98",
    "twitter": "",
    "discord": ""
  }
}

=== eco-stake/validator-registry/src/validator-registry/ChainTools/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "ChainTools",
  "identity": "1857FF1BC2EA6A69",
  "website": "https://chaintools.tech",
  "contacts": {
    "telephone": "",
    "email": "contact@chaintools.tech",
    "telegram": "chaintoolsT",
    "twitter": "chaintoolsT",
    "others": {
      "emergency": ""
    }
  }
}
