=== eco-stake/validator-registry/src/validator-registry/profile.schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"title": "Root", 
	"type": "object",
	"required": [
		"name"
	],
	"properties": {
		"name": {
			"$id": "#root/name", 
			"title": "Name", 
			"type": "string",
			"default": "",
			"examples": [
				"ECO Stake ðŸŒ±"
			],
			"pattern": "^.*$"
		},
		"identity": {
			"$id": "#root/identity", 
			"title": "Identity", 
			"type": "string",
			"default": "",
			"examples": [
				"5992A6D423A406D6"
			],
			"pattern": "^.*$"
		},
		"website": {
			"$id": "#root/website", 
			"title": "Website", 
			"type": "string",
			"default": "",
			"examples": [
				"https://ecostake.com"
			],
			"pattern": "^http.*$"
		},
		"description": {
			"$id": "#root/description", 
			"title": "Description", 
			"type": "object",
			"required": [
				"overview"
			],
			"properties": {
				"overview": {
					"$id": "#root/description/overview", 
					"title": "Overview", 
					"type": "string",
					"default": "",
					"pattern": "^.*$"
				},
				"team": {
					"$id": "#root/description/team", 
					"title": "Team", 
					"type": "string",
					"default": "",
					"pattern": "^.*$"
				},
				"security": {
					"$id": "#root/description/security", 
					"title": "Security", 
					"type": "string",
					"default": "",
					"pattern": "^.*$"
				}
			}
		},
		"contacts": {
			"$id": "#root/contacts", 
			"title": "Contacts", 
			"type": "object",
			"required": [],
			"properties": {
				"telephone": {
					"$id": "#root/contacts/telephone", 
					"title": "Telephone", 
					"type": "string"
				},
				"email": {
					"$id": "#root/contacts/email", 
					"title": "Email", 
					"type": "string"
				},
				"telegram": {
					"$id": "#root/contacts/telegram", 
					"title": "Telegram", 
					"type": "string"
				},
				"twitter": {
					"$id": "#root/contacts/twitter", 
					"title": "Twitter", 
					"type": "string"
				},
				"discord": {
					"$id": "#root/contacts/discord", 
					"title": "Discord", 
					"type": "string"
				},
				"others": {
					"$id": "#root/contacts/others", 
					"title": "Others", 
					"type": "object",
					"required": [],
					"additionalProperties": true
				}
			}
		}
	}
}

=== eco-stake/validator-registry/src/validator-registry/RockawayXInfra/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "RockawayX Infra",
  "identity": "EB935356000A9562",
  "website": "https://rockawayx.com/infrastructure",
  "description": {
    "overview": "RockawayX Infra is enterprise-grade bare-metal staking and infrastructure service provider for decentralized blockchain projects.",
    "team": "Our team has combined over 40 years experience in infrastructure operation, mainly on e-commerce projects.",
    "security": "We stick to 'least possible keys on server' rule, the vast majority of our keys are stored on hardware devices"
  },
  "contacts": {
    "telephone": "",
    "email": "infra@rockawayx.com",
    "telegram": "https://t.me/rockawayx_infra",
    "twitter": "RockawayX_Infra",
    "discord": "",
    "others": {
      "emergency": ""
    }
  }
}

=== eco-stake/validator-registry/src/validator-registry/validator-run/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "Validator.run",
  "identity": "2CC4D67B2136C051",
  "website": "https://validator.run/",
  "description": {
    "overview": "Validator.run is supporter of next-level blockchain infrastructure and staking services.",
    "team": "We are the Validator.run team - a professional PoS validator, that is focused on blockchain consumers & validators. We help teams to easily join the Cosmos SDK community and make their project valuable."
  },
  "contacts": {
    "email": "contact@validator.run",
    "telegram": "arda1975",
    "twitter": "ValidatorRun"
  }
}

=== eco-stake/validator-registry/Staketab/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "Staketab",
  "identity": "72200AE6CB11A0DE",
  "website": "https://staketab.com/",
  "description": {
    "overview": "Professional staking provider offering infrastructure solutions for the Web3 ecosystem.",
    "team": "As a team we are dedicated to development of Web3. As we stake in a blockchain, we aim to make a considerable contribution in one."
  },
  "contacts": {
    "telephone": "",
    "email": "partners@staketab.com",
    "telegram": "ducca",
    "twitter": "staketab",
    "discord": "duccaofficial",
    "others": {
      "emergency": "support@staketab.com"
    }
  }
}

=== eco-stake/validator-registry/src/validator-registry/AMSolutions/profile.json
{
   "$schema":"../profile.schema.json",
   "name":"AM Solutions",
   "identity":"5A1DB2A1F7B6A66F",
   "website":"https://www.theamsolutions.info",
   "description":{
      "overview":"AM Solutions validating many great projects at Cosmos ecosystem. Our goal is to provide maximum safety staking experience for our delegators."
   },
   "contacts":{
      "telephone":"",
      "email":"mannaxriga@gmail.com",
      "telegram":"@AlekseyRiga",
      "twitter":"",
      "discord":"AlexeyM#5409",
      "others":{
         "emergency":""
      }
   }
}

=== eco-stake/validator-registry/src/validator-registry/CryptoCats.Pro/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "CryptoCats.Pro",
  "identity": "FA902B6D69CA60C1",
  "website": "https://cryptocats.pro",
  "description": {
    "overview": "Building trust, block by block.",
    "team": "A team of cryptolovers and tech experts specialized in validating blockchains."
  },
  "contacts": {
    "telephone": "",
    "email": "catomatik@gmail.com",
    "telegram": "catomatik",
    "twitter": "@catomatik",
    "discord": "cwt#3491",
    "others": {
      "emergency": ""
    }
  }
}

=== eco-stake/validator-registry/owlstake/profile.json
{
	"$schema": "../profile.schema.json",
	"name": "owlstake",
	"identity": "6B73E2068E0C0C4C",
	"website": "https://owlstake.com",
	"description": {
		"overview": "VENTURING WITH US!",
		"team": "We are a Professional Validator of PoS Cryptocurrencies who helps investors and token holders gain profits from their assets by consistently increasing their yields via non-custodial staking. Join us, stake, and earn."
	},
	"contacts": {
		"telephone": "",
		"email": "work@owlstake.com",
		"telegram": "bettermanzZ",
		"twitter": "owlstake",
		"discord": "owlstake",
		"others": {
			"emergency": ""
		}
	}
}

=== eco-stake/validator-registry/SynergyNodes/profile.json
{
  "$schema": "../profile.schema.json",
  "name": "Synergy Nodes",
  "identity": "AF9D7EF7CC70CE24",
  "website": "https://www.synergynodes.com",
  "description": {
    "overview": "Synergy Nodes operates validator nodes for multiple Cosmos chains and also provide core infrastructure support for various blockchain protocols.",
    "team": "Synergy Nodes is founded by couple of full time crypto & blockchain technology enthusiast who are committed to helping build core infrastructure for various blockchain protocols."
  },
  "contacts": {
    "telephone": "",
    "email": "contact@synergynodes.com",
    "telegram": "https://t.me/SynergyNodes",
    "twitter": "https://twitter.com/SynergyNodes",
    "discord": "https://discord.gg/UEppF4sBdM",
    "others": {
      "emergency": ""
    }
  }
}

=== eco-stake/validator-registry/Quasar/profile.json
{
    "$schema": "../profile.schema.json",
    "name": "Quasar",
    "identity": "BAD2060A89C6E9D4293754344241D5A16BC4F451",
    "website": "https://quasarstaking.ai",
    "description": {
      "overview": "Building AI neuroworkers for Cosmos community."
    },
    "contacts": {
    "twitter": "https://x.com/quasarstaking",
    "telegram": "https://t.me/quasarstakingeng",
    "discord": "https://discord.gg/CjHRz6dr"
  }
}
